# Week 1

In the first week we had a talk about the course syllabus and discussed about Machine Learning examples.

For the second week we will do a refresher on Python. Please bring your laptops and install Anaconda with Python 3.7.

## Install Anaconda

1. Install Anaconda   
  https://www.anaconda.com/distribution/#download-section
2. Click on start menu and choose anaconda prompt’(windows) OR run terminal (osx/ubuntu)
3. Create a virtual environment (e.g. ‘mbl-ml’, could be any name you like):  
• > conda create -n mbl-ml python=3.7 ipykernel
4. Activate the virtual environment:  
• > source activate mbl-ml
5. Install dependencies:  
• Change directory to where the given file (requirements.txt) resides.  
• > cd (just drag your folder into the cmd/terminal)  
• > pip install -r requirements.txt  
6. Make kernel accessible in jupyter notebook:  
• > python -m ipykernel install --user --name mbl-ml  
7. Go to the directory that you would like to save your notebooks
• > cd (just drag your folder into the cmd/terminal)
8. Run jupyter notebook:
• > jupyter notebook
9. Create new file and set kernel to ‘mbl-ml’
10. To shut down jupyter:
• Press cmd ‘C’ or > ctrl ‘C’ at the terminal/cmd prompt
11. To deactivate virtual environment:
• > conda deactivate
